Django_Project_Pets/Django_Project_Pets/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pets.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Project_Pets/pets/urls.py
from django.urls import path

from pets import views

app_name = 'pets'

urlpatterns = [
    path('', views.home, name='home'),
    # cart urls segment
    path('product_list/', views.product_list, name='product_list'),
    path('logout/', views.logout, name='logout'),
    path('cart/', views.view_cart, name='view_cart'),

    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    # payment urls
    path('payment/<int:amount>/', views.payment, name='payment'),
    # user urls segment
    path('profile/', views.client_profile, name='client_profile'),
    path('<int:pk>/', views.client_details, name='client_details'),
    path('<int:pk>/edit/', views.edit_profile, name='edit_profile'),
    path('<int:pk>/delete/', views.delete_profile, name='delete_profile'),

]

Django_Project_Pets/pets/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.name


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quantity} * {self.product.name}'


class ClientProfile(models.Model):
    client_name = models.CharField(max_length=200)
    client_bio = models.TextField()
    profile_image = models.ImageField(upload_to='profile/')
    dat_created = models.DateTimeField(auto_now_add=True)
    data_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.client_name

    def edit(self, client_name, client_bio, profile_image):
        self.client_name = client_name
        self.client_bio = client_bio
        self.profile_image = profile_image
        self.save()

Django_Project_Pets/pets/forms.py
from django import forms

from pets.models import ClientProfile


class ClientForm(forms.ModelForm):
    class Meta:
        model = ClientProfile
        fields = ['client_name', 'client_bio', 'profile_image']

Django_Project_Pets/pets/views.py
from allauth.socialaccount.models import SocialAccount
from django.shortcuts import render, redirect, get_object_or_404
from django_daraja.mpesa.core import MpesaClient

from pets.forms import ClientForm
from pets.models import Product, CartItem, ClientProfile


# Create your views here.
def home(request):
    return render(request, 'my cart items/login.html')


def logout(request):
    logout(request)
    return redirect('')


def redirect_to_welcome(user):
    if SocialAccount.objects.filter(user=user, provider='google').exists():
        return redirect('welcome')  # Redirect to welcome page if authenticated via Google
    else:
        return redirect('home')  # Redirect to home page if authenticated via other means


def product_list(request):
    products = Product.objects.all()
    return render(request, 'index.html', {'products': products})


def view_cart(request):
    cart_items = CartItem.objects.filter(user=request.user)
    total_price = sum(item.product.price * item.quantity for item in cart_items)
    return render(request, 'my cart items/cart.html', {'cart_items': cart_items, 'total_price': total_price})


def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    cart_item, created = CartItem.objects.get_or_create(product=product, user=request.user)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('pets:view_cart')


def remove_from_cart(request, item_id):
    cart_item = CartItem.objects.get(id=item_id)
    cart_item.delete()
    return redirect('pets:view_cart')


def payment(request, amount):
    if request.method == 'POST':
        mc = MpesaClient()
        account_reference = 'reference'
        transaction_description = 'Shopping List'
        phoneno = request.POST['phoneno']
        amount = int(request.POST['amount'])
        callback_url = 'https://api.darajambili.com/express-payment'
        mc.stk_push(phoneno, amount, account_reference, transaction_description, callback_url)
        message = f'Your payment was successfully'
        return render(request, 'my cart items/user.html', {'message': message, })
    else:
        return render(request, 'my cart items/user.html', {'amount': amount})


def client_profile(request):
    profile = ClientProfile.objects.all()
    return render(request, 'landing.html', {'profile': profile})


def client_details(request, pk):
    client_info = ClientProfile.objects.all(pk=pk)
    return render(request, 'editing/main.html', {'client_info': client_info})


def edit_profile(request, pk):
    client_info = get_object_or_404(ClientProfile, pk=pk)
    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES, instance=client_info)
        if form.is_valid():
            form.save()
            return redirect('pets:client_profile')

    else:
        form = ClientForm(instance=client_info)
    return render(request, 'editing/edit.html', {'form': form})


def delete_profile(request, pk):
    client_info = get_object_or_404(ClientProfile, pk=pk)
    if request.method == 'POST':
        client_info.delete()
        return redirect('client_profile')
    return render(request, 'editing/delete.html', {'client_info': client_info})

Django_Project_Pets/templates/editing/delete.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h2>Delete Profile Details</h2>
<p>Are you sure you want to get rid of me . Please {{ user_info.user_name }}</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Goodbye Profile</button>
</form>

</body>
</html>

Django_Project_Pets/templates/editing/edit.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h2>Let edit here</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save New Look</button>
</form>
</body>
</html>

Django_Project_Pets/templates/editing/main.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>


<h1>{{ client_info.client_name }}</h1>
<div>
    <img src="{{ client_info.profile_image }}" alt="{{ client_info.client_name }}">
</div>
<p>{{ client_info.client_name }}</p>
<p>{{ client_info.client_bio }}</p>
<button><a href="{% url 'edit_profile' client_info.pk %}">Edit</a></button>
<button><a href="{% url 'delete_profile' client_info.pk %}">Delete</a></button>


<a href="{% url 'pets:client_profile' %}">Back to Homepage</a>
</body>
</html>

Django_Project_Pets/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
	<title>Product Catalog</title>
	<style>

		.product-list {
			display: flex;
			flex-wrap: wrap; 
			justify-content: space-between; 
			list-style: none; 
			padding: 0;
		}

		.product-item {
			flex: 1; 
			max-width: 30%; 
			margin: 10px; 
			border: 1px solid #ccc;
			padding: 10px;
			text-align: center;
		}

		/* Style the "Buy Now" button */
		.buy-now-button {
			display: block;
			margin-top: 10px;
			background-color: #007bff;
			color: #fff;
			text-decoration: none;
			padding: 5px 10px;
			border-radius: 5px;
		}
	</style>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
        <a class="navbar-brand" href="#">Fashion_fiesta</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
          <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'pets:product_list' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'pets:client_profile' %}">My Profile </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'pets:view_cart' %}">My Cart</a>
      </li>
    </ul>
  </div>

</nav>
	<h1 style="text-align: center; text-decoration: none;font-family: 'Book Antiqua',fantasy">Product Catalog</h1>
     <div class="mt-4 p-5 bg-primary text-white rounded"  >
         <h1 style="text-align: center; font-family: Broadway,fantasy" >Fashionista</h1>
     </div>
	
	<ul class="product-list">
		{% for product in products %}
			<li class="product-item">
				<img src="{{ product.image.url }}" alt="{{ product.name }}" width="200" height="150">
				<h2>{{ product.name }}</h2>
				<p>{{ product.description }}</p>
				<p>Price: Kes:{{ product.price }}</p>
                {% with Price=product.price|floatformat:"0" %}

                    <a href="{% url 'pets:payment' Price %}" class="buy-now-button">Buy Now</a>
                {% endwith %}
				<a class="buy-now-button" href="{% url 'pets:add_to_cart' product.id %}">Add to Cart</a>
			</li>
		{% endfor %}
	</ul>
</body>
</html>

Django_Project_Pets/templates/landing.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<style>
    body{
        background-color: firebrick;
        font-family: "Old English Text MT";
    }
     img{
        border-radius: 50%;
        display: block;
        margin-left:auto ;
        margin-right: auto;
        width: 50%;
    }
    button{
        background-color: darkviolet;
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline;        
    }
</style>
<body>
{% for p in profile %}
        <h1 style="text-align: center;animation-play-state:paused;font-family: 'Times New Roman',fantasy ">{{ p.client_name }}</h1>
    <a href="{% url 'pets:client_details' p.pk %}">
        <img src="{{ p.profile_image.url }}" alt=""></a>

    <p>{{ p.client_bio }}</p>
    <button><a href="{% url 'pets:edit_profile' p.pk %}">Edit</a></button>
    <button><a href="{% url 'pets:delete_profile' p.pk %}">Delete</a></button>
    
{% endfor %}
<a style="background-color: gold" href="{% url 'pets:product_list' %}">Back to Home</a>
</body>
</html>

Django_Project_Pets/templates/my cart items/cart.html
<!-- cart/cart.html -->

<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<style>

		.product-list {
			display: flex;
			flex-wrap: wrap; 
			justify-content: space-between; 
			list-style: none;
			padding: 0;
		}

		.product-item {
			
			flex: 1; 
			
			margin: 10px; 
			border: 1px solid #ccc;
			padding: 10px;
			text-align: center;
		}

		/* Style the "Buy Now" button */
		.buy-now-button {
			display: block;
			margin-top: 10px;
			background-color: #007bff;
			color: #fff;
			text-decoration: none;
			padding: 5px 10px;
			border-radius: 5px;
		}
	</style>
</head>

<body>

	<h1>Your Shopping Cart</h1>

	<div class="product-list">

	

	{% for item in cart_items %}
	<div class="product-item">
		<p>{{ item.product.name }} ({{ item.quantity }})</p>
        <img src="{{ item.product.image.url }}" alt="{{ product.name }}" width="200" height="150">
		<p>Price: Ksh:{{ item.product.price }}</p>
		<a href="{% url 'pets:remove_from_cart' item.id %}">Remove</a>
	</div>
	{% empty %}
	<p>Your cart is empty.</p>
	{% endfor %}

	</div>

	<p>Total Price: Ksh:{{ total_price }}</p>
    {% with Price=total_price|floatformat:"0" %}

                    <a href="{% url 'pets:payment' Price %}" class="buy-now-button">Buy Now</a>
                {% endwith %}
   


	<a href="{% url 'pets:product_list' %}">Continue Shopping</a>

</body>

</html>

Django_Project_Pets/templates/my cart items/contact Me.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact Me</title>
</head>
<body>

</body>
</html>

Django_Project_Pets/templates/my cart items/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% load socialaccount %}
{% block content %}
    <h1>Google Login</h1>
    <button>
{#            <a href="{% provider_login_url 'google' %}">Login with Google</a>#}
    <a href="{% provider_login_url 'google' %}?next=/product_list/">Login with Google</a>
    </button>
    {% if user is authenticated %}
        <h3>{{ user.email }} has logged in successfully </h3>
        <p>Proceed to fashionnista <a href="{% url 'pets:product_list' %}"></a></p>
        <a href="#">Logout</a>
    {% endif %}
{% endblock %}
</body>
</html>

Django_Project_Pets/templates/my cart items/user.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>Document</title>
</head>
<style>
    {
    form {
        input[type=submit] {
            background-color: darkturquoise;
            color: snow;
            padding: 12px 20px;
            border-radius: 4px;
            cursor: pointer;
            float: right;

        }
    }

    }
</style>
<body>
<form method="post" action="{% url 'pets:payment' 3 %}">
    {% csrf_token %}
    <input type="number" placeholder="phone no" value="" name="phoneno" >
    <input type="number" placeholder="amount" value="{{ amount }}" name="amount">
      
    <button type="submit">SEND</button>
</form>
</body>
</html>